const $=id=>document.getElementById(id);
let authMode='login';
function show(id,btn){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');refresh()}
async function refresh(){const r=await fetch('/api/state');const s=await r.json();$('farmerName').textContent=s.farmer.name;$('farmerId').textContent=s.farmer.id;$('balance').textContent='₹'+s.balance.toLocaleString();$('walletBalance').textContent=s.balance.toLocaleString();$('statusTitle').textContent=s.policy_active?'Policy active':'No active policy';$('statusText').textContent=s.policy_active?'Protected automatically by rainfall trigger.':'Activate the ₹300 RainShield policy to begin.'; $('history').innerHTML=s.history.length?s.history.map(x=>`<div class="timeline"><div><b>${x.type}</b><br>${x.amount>=0?'+':''}₹${Math.abs(x.amount).toLocaleString()}<br><small>${x.reason}</small></div></div>`).join(''):'<p>No transactions yet.</p>'}
async function bindPolicy(){if(!$('understood').checked){$('bindMsg').textContent='Please listen/read the explanation and confirm understanding first.';return}await fetch('/api/bind',{method:'POST'});$('bindMsg').textContent='✓ Policy activated.';refresh()}
async function evaluate(){const vals=[+$('o1').value,+$('o2').value,+$('o3').value];const r=await fetch('/api/oracles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:vals})});const d=await r.json();$('decision').innerHTML=`Readings: <b>${vals.join(' / ')} mm</b><br>Median: <b>${d.median} mm</b><br><br>${d.triggered?'🟢 TRIGGERED — payout ₹'+d.payout.toLocaleString():'🔵 NO PAYOUT — rainfall is above the threshold'}`;refresh()}
function scenario(x){if(x==='normal')[$('o1').value,$('o2').value,$('o3').value]=[18,19,17];if(x==='compromised')[$('o1').value,$('o2').value,$('o3').value]=[2,3,85];if(x==='stale')[$('o1').value,$('o2').value,$('o3').value]=[18,19,90];evaluate()}
function speak(){if('speechSynthesis' in window){speechSynthesis.cancel();const message=new SpeechSynthesisUtterance('Your RainShield premium is three hundred rupees. If verified rainfall is below twenty millimetres, forty percent of your twenty thousand rupee coverage is paid automatically. No claim form is required.');const voices=speechSynthesis.getVoices();const femaleVoice=voices.find(voice=>/female|samantha|karen|zira|susan|hazel|libby|google uk english female/i.test(voice.name));if(femaleVoice)message.voice=femaleVoice;speechSynthesis.speak(message)}}
async function resetApp(){await fetch('/api/reset',{method:'POST'});refresh();alert('Demo reset.')} 
function openAuth(){$('authModal').classList.add('open');$('authModal').setAttribute('aria-hidden','false');$('authEmail').focus()}
function closeAuth(event){if(!event||event.target===$('authModal')){$('authModal').classList.remove('open');$('authModal').setAttribute('aria-hidden','true');$('authMessage').textContent=''}}
function setAuthMode(mode){authMode=mode;$('loginTab').classList.toggle('selected',mode==='login');$('signupTab').classList.toggle('selected',mode==='signup');$('nameField').classList.toggle('hidden',mode==='login');$('authName').required=mode==='signup';$('passwordRules').classList.toggle('hidden',mode==='login');$('authSubmit').textContent=mode==='login'?'Log in':'Create account';$('authTitle').textContent=mode==='login'?'Welcome back':'Create your account';$('authIntro').textContent=mode==='login'?'Log in to keep your policy and wallet close at hand.':'Sign up to save your RainShield account details.';$('authMessage').textContent=''}
async function submitAuth(event){event.preventDefault();const payload={email:$('authEmail').value,password:$('authPassword').value};if(authMode==='signup')payload.name=$('authName').value;const r=await fetch('/api/auth/'+authMode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok){$('authMessage').textContent=data.error;return}updateAccount(data.user);closeAuth()}
function updateAccount(user){$('accountButton').textContent=user?user.name:'Log in';$('accountButton').classList.toggle('logged-in',!!user);$('accountButton').onclick=user?logout:openAuth}
async function logout(){await fetch('/api/auth/logout',{method:'POST'});updateAccount(null)}
window.addEventListener('online',()=>{$('net').textContent='● Online';$('net').style.background='#e8f5e9'});window.addEventListener('offline',()=>{$('net').textContent='● Offline';$('net').style.background='#fff0e9'});fetch('/api/auth/session').then(r=>r.json()).then(data=>updateAccount(data.user));refresh();
